name: brightapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  provider: ^6.0.5
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  firebase_messaging: ^15.1.3
  photofilters: ^3.0.1 
  image: ^3.3.0
  image_cropper: ^8.0.2 
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0 # Add the flutter_launcher_icons dependency

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/google.png
    - assets/images/facebook.png
    
# Configuration for flutter_launcher_icons
flutter_icons:
  android: true    # Enable custom icons for Android
  ios: true        # Enable custom icons for iOS (if applicable)
  image_path: "assets/images/app_icon.png"  # Path to your app icon image
